; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
lib_ldf_mode = chain+
framework = arduino
; CVIDEO_INTERLACED=0 -> progressive 288p output (default)
; CVIDEO_INTERLACED=1 -> interlaced 576i field output
build_flags = -std=gnu++23 -DCVIDEO_INTERLACED=0

lib_deps = 
    arkhipenko/TaskScheduler@^4.0.4
    rlogiacco/CircularBuffer@^1.4.0
    rweather/Crypto @ ^0.4.0

board_build.f_cpu =  250000000L
board_build.core = earlephilhower

upload_protocol = jlink
debug_tool = jlink
