// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define CLOCKS_PER_BIT 6

// ------ //
// cvsync //
// ------ //

#define cvsync_wrap_target 0
#define cvsync_wrap 18
#define cvsync_pio_version 0

static const uint16_t cvsync_program_instructions[] = {
            //     .wrap_target
    0xfe24, //  0: set    x, 4            side 1 [14]
    0xa042, //  1: nop                    side 0
    0x1e41, //  2: jmp    x--, 1          side 1 [14]
    0xed24, //  3: set    x, 4            side 0 [13]
    0x1126, //  4: jmp    !x, 6           side 1 [1]
    0x0d44, //  5: jmp    x--, 4          side 0 [13]
    0xfd23, //  6: set    x, 3            side 1 [13]
    0xb042, //  7: nop                    side 1
    0xa042, //  8: nop                    side 0
    0x1e48, //  9: jmp    x--, 8          side 1 [14]
    0xe130, // 10: set    x, 16           side 0 [1]
    0xbe42, // 11: nop                    side 1 [14]
    0x1e2e, // 12: jmp    !x, 14          side 1 [14]
    0x014b, // 13: jmp    x--, 11         side 0 [1]
    0xa127, // 14: mov    x, osr          side 0 [1]
    0xb242, // 15: nop                    side 1 [2]
    0xdd00, // 16: irq    nowait 0        side 1 [13]
    0x1c20, // 17: jmp    !x, 0           side 1 [12]
    0x014f, // 18: jmp    x--, 15         side 0 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cvsync_program = {
    .instructions = cvsync_program_instructions,
    .length = 19,
    .origin = -1,
    .pio_version = cvsync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cvsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cvsync_wrap_target, offset + cvsync_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ------ //
// cvdata //
// ------ //

#define cvdata_wrap_target 0
#define cvdata_wrap 4
#define cvdata_pio_version 0

static const uint16_t cvdata_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0
    0xa041, //  1: mov    y, x
    0x20c0, //  2: wait   1 irq, 0
    0x6401, //  3: out    pins, 1                [4]
    0x0083, //  4: jmp    y--, 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program cvdata_program = {
    .instructions = cvdata_program_instructions,
    .length = 5,
    .origin = -1,
    .pio_version = cvdata_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config cvdata_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + cvdata_wrap_target, offset + cvdata_wrap);
    return c;
}
#endif

